services:
  db:
    image: postgres:14-alpine
    container_name: pharmacy_db
    restart: always
    environment:
      POSTGRES_DB: pharmacy
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: pharmacy_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pharmacy_app
    restart: always
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pharmacy
      SPRING_DATASOURCE_USERNAME: pharmacy_user
      SPRING_DATASOURCE_PASSWORD: pharmacy_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  db_data:
